### ISSUE TITLE
Access model checkpoint from AWS S3

### ISSUE THREAD

**Issue by rcruzgar** [aws-samples/amazon-sagemaker-pytorch-detectron2#13]
Hi there!

I am trying to make predictions on a AWS Batch Job using model weights (checkpoint) stored on a S3 bucket, this way:

```
from detectron2.config import get_cfg
from detectron2.engine import DefaultPredictor

cfg = get_cfg()
cfg.MODEL.WEIGHTS = 's3://bucket/folder/model_final.pth'
predictor = DefaultPredictor(cfg)
outputs = predictor(side_dish_image)
```

However, the docker job doesn't seem to have a direct connection with the S3 bucket, and I get the following:

```
AssertionError: Checkpoint s3://bucket/folder/model_final.pth not found!
```

Is there a way I can access the checkpoint from S3? I would prefer to avoid creating an endpoint for inference (I haven't tried it yet).

*EDIT*: Also, I could copy it to the Docker, but that's highly inefficient (335 MB).

Best regards,
Rubén.

**Comment by paoloirrera** [comment]
Hello,

Docker containers in this repository are supposed to be used in SageMaker. Did you look at the tutorial [d2_custom_sku110k.ipynb](https://github.com/aws-samples/amazon-sagemaker-pytorch-detectron2/blob/main/d2_custom_sku110k.ipynb)? It presents how to predict in a SageMaker Batch Transform. I think that this can address your pain-point.
