### ISSUE TITLE
The repository with name 'pytorch-training' does not exist

### ISSUE THREAD

**Issue by lehigh123** [aws-samples/amazon-sagemaker-pytorch-detectron2#14]
When running the 

```
%%bash
./build_and_push.sh sagemaker-d2-train-sku110k latest Dockerfile.sku110ktraining
```

cell there is a docker error 

```
repository 663822598777.dkr.ecr.us-east-1.amazonaws.com/pytorch-training not found: name unknown: The repository with name 'pytorch-training' does not exist in the registry with id '663822598777'
```

**Comment by lehigh123** [comment]
I think you might be able to solve this by updating the DockerFile.sku100ktraining 


```
ARG REGION
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.6.0-gpu-py36-cu101-ubuntu16.04
```

**Comment by paoloirrera** [comment]
Please check again the file [Dockerfile.sku110ktraining](https://github.com/aws-samples/amazon-sagemaker-pytorch-detectron2/blob/main/Dockerfile.sku110ktraining), there is no reference to the call that you mentioned  and the id of the ECR registry is 763104351884.
