### ISSUE TITLE
Docker required

### ISSUE THREAD

**Issue by robmarkcole** [aws-samples/amazon-sagemaker-pytorch-detectron2#3]
To push to ECR docker must be on the sagemaker instance, which it is not by default and must be installed else error `docker: command not found` is returned. Please can the install instructions be included

**Comment by paoloirrera** [comment]
I cannot reproduce this error as Docker is by default installed in SageMaker notebook instances. In which region are you?

**Comment by robmarkcole** [comment]
Sorry this is sagemaker studio in `eu-west-2`

**Comment by paoloirrera** [comment]
The environments that I tested were:

- EC2
- SageMaker notebook instances

Both in eu-west-1. Do you need to work in SageMaker studio?

**Comment by robmarkcole** [comment]
NP I can use one of those, cheers
