### ISSUE TITLE
Question regarding incremental training

### ISSUE THREAD

**Issue by michaelmohamed** [aws-samples/amazon-sagemaker-pytorch-detectron2#6]
Hello, does this repo support incremental training?

Can I provide a model as a starting point for training, versus starting from scratch?

https://docs.aws.amazon.com/sagemaker/latest/dg/incremental-training.html

Regards,

M

**Comment by paoloirrera** [comment]
Hello, the training process is not from scratch, but it uses Detectron2's weights from the model zoo as initialization. You could initialize the network with weights from a checkpoint or a previous training session. 

However, The container does not implement incremental training as per parsing `model_uri` parameter of `Estimator` class of SageMaker API.
