### ISSUE TITLE
deploy trained model as endpoint

### ISSUE THREAD

**Issue by fgraffitti-cyberhawk** [aws-samples/amazon-sagemaker-pytorch-detectron2#7]
I have been trying to re-adapt your code to deploy the trained model as an endpoint, but I am having some troubles when trying to send images to the endpoint to get a prediction.
A detailed explanation of the problem can be found here: https://stackoverflow.com/questions/70033312/invoke-endpoint-error-detectron2-on-aws-sagemaker-valueerror-type-applicati

Any idea of how to solve this problem, or suggestion on how to perform single-image inference rather than batch transform?

**Comment by paoloirrera** [comment]
Hello the error message indicates that your sending data of type `[application/x-npy]` which the script does not support. You can try to extend the `input_fn` function as it follows:

```
from sagemaker_inference decoder
# from sagemaker.content_types import CONTENT_TYPE_JSON, CONTENT_TYPE_CSV, CONTENT_TYPE_NPY # TODO: for local debug only. Remove or comment when deploying remotely.

def input_fn(request_body: BinaryIO, request_content_type: str) -> np.ndarray:
    r"""Parse input data

    Parameters
    ----------
    request_body : BinaryIO
        encoded input image
    request_content_type : str
        type of content

    Returns
    -------
    np.ndarray
        input image

    Raises
    ------
    ValueError
        ValueError if the content type is not `application/x-image`
    """
    if request_content_type == "application/x-image":
        np_image = _load_from_bytearray(request_body)
    elif request_content_type == "application/x-npy":
        np_image = decoder.decode(request_body, CONTENT_TYPE_NPY)
    else:
        err_msg = f"Type [{request_content_type}] not support this type yet"
        LOGGER.error(err_msg)
        raise ValueError(err_msg)
    return np_image
```

**Comment by fgraffitti-cyberhawk** [comment]
> 

Yeah, at the end I managed to change the input file to accept either json or x-npy format. Thanks for your answer :)
