### ISSUE TITLE
Change Serve Dockerfile to automatically include the inference code

### ISSUE THREAD

**Issue by AliButtar** [aws-samples/amazon-sagemaker-pytorch-detectron2#9]
Hi,

I want to change the serve Dockerfile in a way that is similar to the training Dockerfile where it defines an entrypoint on its own. 

The reason for this is that I do not want to pass anything in the source directory parameter when building the model so that the training artifact can be used directly. 

For Example: 

```
model = PyTorchModel(
    name="d2-model",
    model_data=training_job_artifact,
    role=role,
    sagemaker_session=sm_session,
    entry_point="predict_det2.py",
    # source_dir="container_serving",
    image_uri=serve_image_uri,
    framework_version="1.6.0",
    code_location=f"s3://{bucket}/{prefix_code}",
)

```
Where the Dockerfile is as this ( I have tried to add multiple lines as entrypoint which I will specify in comments):
```
# Build an image of Detectron2 with Sagemaker Multi Model Server: https://github.com/awslabs/multi-model-server

# using Sagemaker PyTorch container as base image
# from https://github.com/aws/sagemaker-pytorch-serving-container/

ARG REGION
FROM 763104351884.dkr.ecr.$REGION.amazonaws.com/pytorch-inference:1.5.1-gpu-py36-cu101-ubuntu16.04
LABEL author="pirrera@amazon.com"

############# Installing latest builds ############
RUN pip install --upgrade torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

# ENV FORCE_CUDA="1"
# Build D2 only for Turing (G4) and Volta (P3) architectures. Use P3 for batch transforms and G4 for inference on endpoints
# ENV TORCH_CUDA_ARCH_LIST="Turing;Volta"

# Install Detectron2
RUN pip install \
   --no-cache-dir pycocotools~=2.0.0 \
   --no-cache-dir https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/detectron2-0.4%2Bcu101-cp36-cp36m-linux_x86_64.whl

# Set a fixed model cache directory. Detectron2 requirement
ENV FVCORE_CACHE="/tmp"

############# SageMaker section ##############

COPY container_serving /opt/ml/code
WORKDIR /opt/ml/code

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
ENV SAGEMAKER_PROGRAM predict_sku110k.py

WORKDIR /

# ENTRYPOINT ["bash", "-m", "start_with_right_hostname.sh"] # As this exists in PyTorch Inference Toolkit "artifact" folder so I thought maybe it could work
# ENTRYPOINT ["python", "predict_sku110k.py"]
ENTRYPOINT ["python", "/opt/ml/code/predict_sku110k.py"]
```

I created a model using the images built from these dockerfiles. The model is created successfully and also shows up on AWS sagemaker console but when I initiate a Batch Transform job it failed because it is not able to locate the `predict_sku110k.py` file. 

Any help would be appreciated, I just want this image to create models that can directly use training artifacts. The reason I have understood so far that it doesn't is because the artifacts do not have a `code` directory inside them which contains this `predict_sku110.py` file. When the model is created however then it uploads a new artifact to S3 with the `code` directory which helps it do inference. 

If somehow this code directory can be bundled inside the training image so that when the training artifact is created it is already there, then that would work as well I presume.

Thanks a lot,
AliButtar

**Comment by paoloirrera** [comment]
This is a sagemaker-inference related question. Please refer to the documentation. I cannot help you with it as not related to the content of the repository.
